# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build bibliography

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyzotero
    - name: Get bibliographic entries 
      run: |
        python bibliography/zotero_citations_copy.py ${{ secrets.ZOTERO_LIBRARY_CODE }} group ${{ secrets.ZOTERO_API_KEY }} bibliography2.md
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      with:
        name: bibliography
        path: bibliography2.md
    - name: Download artifact
      # You may pin to the exact commit or the version.
      # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
      uses: aochmann/actions-download-artifact@1.0.4
      with:
        # GitHub token
       # github_token: # optional, default is ${{github.token}}
        # Repository name with owner
        # repo: # optional, default is ${{github.repository}}
        # Artifact name (download all artifacts in not specified)
        name: bibliography # optional
        # Download latest artifact
        # latest: # optional
        # Artifact unpack location
       #  path: # optional, default is ./
   
